version: "3"

services:
    www:
        build: .
        restart: always
        ports:
            - '8080:80'
        volumes:
            - ./www:/var/www/html
        networks:
            - default
    db:
        image: mysql:5.7
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_DATABASE: dockerdb
            MYSQL_USER: mysql
            MYSQL_PASSWORD: '123@Mudar'
            MYSQL_ROOT_PASSWORD: '123@Mudar'
        volumes:
            - db_data:/var/lib/mysql
        networks:
            - default

volumes:
    db_data: